// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAoPUKItE2pu1SBhO1a0CtjV8ZNlYXxCI',
    appId: '1:665436151650:web:96c178a53d2c8b17e2d63b',
    messagingSenderId: '665436151650',
    projectId: 'hotels-pfe',
    authDomain: 'hotels-pfe.firebaseapp.com',
    storageBucket: 'hotels-pfe.appspot.com',
    measurementId: 'G-KXVC3G9W3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GeUFaOaWvn13jdy6JETr27ooUx1jwH8',
    appId: '1:665436151650:android:306d62197b866954e2d63b',
    messagingSenderId: '665436151650',
    projectId: 'hotels-pfe',
    storageBucket: 'hotels-pfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHbfLYsC9_xKfboC3duZ-vo7DbJpP6uU',
    appId: '1:665436151650:ios:caf73701ef073738e2d63b',
    messagingSenderId: '665436151650',
    projectId: 'hotels-pfe',
    storageBucket: 'hotels-pfe.appspot.com',
    iosBundleId: 'com.example.flutterPfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHbfLYsC9_xKfboC3duZ-vo7DbJpP6uU',
    appId: '1:665436151650:ios:b37dedcc8e12a6dee2d63b',
    messagingSenderId: '665436151650',
    projectId: 'hotels-pfe',
    storageBucket: 'hotels-pfe.appspot.com',
    iosBundleId: 'com.example.flutterPfe.RunnerTests',
  );
}
